### ISSUE TITLE
Map storytelling with routes

### ISSUE THREAD

**Issue by cedricdelpoux** [pomber/gatsby-waves#14]
Hi, 

Do you know a way to add routes to the storytelling ?

I could be awesome to achieve something like [this](https://tympanus.net/Development/StorytellingMap/) with your plugin

**Comment by pomber** [comment]
If [pidgeon-maps](https://github.com/mariusandra/pigeon-maps) supports it, it should be possible.

You can also copy the [maps-wave](https://github.com/pomber/gatsby-waves/blob/master/demo/src/components/maps/maps-wave.js) component and modify it to use another map provider

**Comment by cedricdelpoux** [comment]
It seems like pidgeon-maps does not support it. [Mapbox storytelling](https://github.com/mapbox/storytelling) neither.

I can't find a way to achieve it using a map library. 
Do you have ideas?

**Comment by pomber** [comment]
google maps maybe? sorry I don't know too much about map libraries.

**Comment by cedricdelpoux** [comment]
Ok thank
