### ISSUE TITLE
Customizing styles from CodeSurfer

### ISSUE THREAD

**Issue by eaverdeja** [pomber/gatsby-waves#16]
Hey Rodrigo! I'm building a tech blog right now and this theme is great! The code transitions are super smooth and make it a joy to read the code.

Quick question: how can I customize styles for the underlying `<CodeSurfer />` component? I checked the docs on CodeSurfer and I saw we can pass a custom theme to it, but it seems that with `gatsby-waves` that is hardcoded [right here](https://github.com/pomber/gatsby-waves/blob/master/theme/src/components/code-sticker.js#L32)

Can I still customize the styles for CodeSurfer in some way?

**Comment by pomber** [comment]
Hi! both packages use theme-ui, so you should be able to override the theme as I do on [my blog](https://github.com/pomber/site/blob/master/src/gatsby-plugin-theme-ui/index.js#L154). You could also spread one of the themes from @code-surfer/themes there too.

**Comment by eaverdeja** [comment]
Hey Rodrigo, thanks for the quick response. Your suggestion worked flawlessly and the `night owl` theme looks GREAT!
